logging:
  level:
    root: INFO

spring:
  application:
    name: camel-account-management
  mvc:
    servlet:
      path: /account_management/v1/api

camel:
  servlet:
    mapping:
        context-path: /account_management/v1/*

server:
  port: 8081

backend:
  url: ${BACKEND_URL:http:localhost:8080/account-management/api/v1}
